module Europe exposing (countries)


countries : List String
countries =
    [ "Albania"
    , "Andorra"
    , "Austria"
    , "Belarus"
    , "Belgium"
    , "Bosnia and Herzegovina"
    , "Bulgaria"
    , "Croatia"
    , "Cyprus"
    , "Czech Republic"
    , "Denmark"
    , "Estonia"
    , "Finland"
    , "France"
    , "Georgia"
    , "Germany"
    , "Greece"
    , "Hungary"
    , "Iceland"
    , "Republic of Ireland"
    , "Italy"
    , "Latvia"
    , "Liechtenstein"
    , "Lithuania"
    , "Luxembourg"
    , "Republic of Macedonia"
    , "Malta"
    , "Moldova"
    , "Monaco"
    , "Montenegro"
    , "Netherlands"
    , "Norway"
    , "Poland"
    , "Portugal"
    , "Romania"
    , "Russia"
    , "San Marino"
    , "Serbia"
    , "Slovakia"
    , "Slovenia"
    , "Spain"
    , "Sweden"
    , "Switzerland"
    , "Turkey"
    , "Ukraine"
    , "United Kingdom"
    , "Vatican City"
    ]
